const DECKS = window.DECKS;
const saveKey = 'target_study_app_v2';
let state = JSON.parse(localStorage.getItem(saveKey) || '{"wrong":{},"star":{},"today":{"date":"","done":0,"ok":0,"ng":0},"history":{},"review":{},"tests":[]}');
function normalizeState(){ state.wrong=state.wrong||{}; state.star=state.star||{}; state.today=state.today||{date:'',done:0,ok:0,ng:0}; state.history=state.history||{}; state.review=state.review||{}; state.tests=state.tests||[]; }
let pool=[], queue=[], current=null, sessionKey='', answerShown=false, lastMark=null;
function todayStr(){ const d=new Date(); const y=d.getFullYear(), m=String(d.getMonth()+1).padStart(2,'0'), day=String(d.getDate()).padStart(2,'0'); return `${y}-${m}-${day}`; }
function displayDate(s){ if(!s) return '-'; const [y,m,d]=s.split('-'); return `${Number(m)}/${Number(d)}`; }
function addDays(s,n){ const d=s?new Date(s+'T00:00:00'):new Date(); d.setDate(d.getDate()+n); const y=d.getFullYear(), m=String(d.getMonth()+1).padStart(2,'0'), day=String(d.getDate()).padStart(2,'0'); return `${y}-${m}-${day}`; }
function ensureToday(){ const t=todayStr(); if(state.today.date!==t) state.today={date:t,done:0,ok:0,ng:0}; state.history[t]=state.history[t]||{done:0,ok:0,ng:0}; }
function save(){ normalizeState(); ensureToday(); localStorage.setItem(saveKey, JSON.stringify(state)); }
function key(deck,no){ return deck+':'+no; }
function allItems(deck){ if(deck==='all') return [...DECKS.t1900.items.map(x=>({...x,deck:'t1900'})), ...DECKS.t1000.items.map(x=>({...x,deck:'t1000'}))]; return DECKS[deck].items.map(x=>({...x,deck})); }
function clamp(n,min,max){ n=Number(n)||min; return Math.max(min, Math.min(max,n)); }
function dueKeys(daysAhead=0){ const target=addDays(todayStr(),daysAhead); return Object.entries(state.review).filter(([k,r])=>r.nextDue && r.nextDue<=target && itemByKey(k)).map(([k])=>k); }
function onDeckChange(){ const deck=document.getElementById('deck').value; const max=deck==='all'?1900:DECKS[deck].max; document.getElementById('startNo').max=max; document.getElementById('endNo').max=max; if(Number(document.getElementById('endNo').value)>max) document.getElementById('endNo').value=max; document.getElementById('deckCount').textContent='v4'; buildPool(); }
function buildPool(){ const deck=document.getElementById('deck').value, src=document.getElementById('source').value; const max=deck==='all'?1900:DECKS[deck].max; const s=clamp(document.getElementById('startNo').value,1,max), e=clamp(document.getElementById('endNo').value,1,max); const a=Math.min(s,e), b=Math.max(s,e); let items=allItems(deck); if(src==='wrong') items=items.filter(w=>state.wrong[key(w.deck,w.no)]); else if(src==='star') items=items.filter(w=>state.star[key(w.deck,w.no)]); else if(src==='review'){ const dueSet=new Set(dueKeys(0)); items=items.filter(w=>dueSet.has(key(w.deck,w.no))); } else items=items.filter(w=>w.no>=a&&w.no<=b); const seen=new Set(); pool=items.filter(w=>{const k=key(w.deck,w.no); if(seen.has(k)) return false; seen.add(k); return true;}); const pc=document.getElementById('poolCount'); if(pc) pc.textContent=pool.length; return pool; }
function getSessionKey(){ return [document.getElementById('deck').value,document.getElementById('source').value,document.getElementById('startNo').value,document.getElementById('endNo').value,document.getElementById('mode').value,document.getElementById('order').value,pool.map(w=>key(w.deck,w.no)).join(',')].join('|'); }
function shuffle(arr){ const a=[...arr]; for(let i=a.length-1;i>0;i--){ const j=Math.floor(Math.random()*(i+1)); [a[i],a[j]]=[a[j],a[i]]; } return a; }
function showNoTarget(msg='対象なし'){ current=null; answerShown=false; setMarkButtons(false); const aa=document.getElementById('answerActions'); if(aa) aa.classList.add('hide'); document.getElementById('qno').textContent='対象なし'; document.getElementById('question').textContent=msg; document.getElementById('answer').style.display='none'; document.getElementById('typed').value=''; }
function startSession(){ buildPool(); if(!pool.length) return showNoTarget('範囲や出題元を変えて'); queue=document.getElementById('order').value==='random'?shuffle(pool):[...pool]; sessionKey=getSessionKey(); updateAll(); nextQuestion(); }
function setMarkButtons(enabled){ const g=document.getElementById('goodBtn'), b=document.getElementById('badBtn'); if(g) g.disabled=!enabled; if(b) b.disabled=!enabled; const aa=document.getElementById('answerActions'); if(aa) aa.classList.toggle('hide', !enabled); }
function finishSession(){ current=null; answerShown=false; setMarkButtons(false); document.getElementById('qno').textContent='この範囲は一周完了'; document.getElementById('question').textContent='もう一周するなら「開始 / 更新」'; document.getElementById('answer').style.display='none'; document.getElementById('typed').value=''; }
function nextQuestion(){ if(!queue.length){ if(!current) return startSession(); return finishSession(); } current=queue.shift(); answerShown=false; setMarkButtons(false); const mode=document.getElementById('mode').value; document.getElementById('qno').textContent=`${DECKS[current.deck].name} No.${current.no}　残り${queue.length}`; document.getElementById('question').textContent=mode==='word2meaning'?current.word:current.meaning; document.getElementById('answer').textContent=mode==='word2meaning'?current.meaning:current.word; document.getElementById('answer').style.display='none'; document.getElementById('typed').value=''; }
function showAnswer(){ if(!current) return; answerShown=true; setMarkButtons(true); document.getElementById('answer').style.display='block'; document.getElementById('answer').scrollIntoView({block:'center',behavior:'smooth'}); }
function updateReview(k,ok){ const t=todayStr(); const r=state.review[k]||{level:0,correctStreak:0,created:t}; if(ok){ r.level=(r.level||0)+1; r.correctStreak=(r.correctStreak||0)+1; const gaps=[1,3,7,14,30,60]; const gap=gaps[Math.min(r.level-1,gaps.length-1)]; r.nextDue=addDays(t,gap); if(r.correctStreak>=3 || r.level>=5) r.graduated=true; } else { r.level=0; r.correctStreak=0; r.nextDue=t; r.graduated=false; } r.last=t; state.review[k]=r; }
function mark(ok){ if(!current) return; if(!answerShown){ alert('先に「答えを見る」を押してから判定して'); return; } ensureToday(); const k=key(current.deck,current.no); lastMark={item:{...current}, ok, date:state.today.date, prevToday:{...state.today}, prevHistory:{...(state.history[state.today.date]||{})}, prevWrong: state.wrong[k]?JSON.parse(JSON.stringify(state.wrong[k])):null, prevReview: state.review[k]?JSON.parse(JSON.stringify(state.review[k])):null}; state.today.done++; ok?state.today.ok++:state.today.ng++; const h=state.history[state.today.date]; h.done++; ok?h.ok++:h.ng++; if(!ok) state.wrong[k]={count:(state.wrong[k]?.count||0)+1,last:new Date().toLocaleDateString('ja-JP'),dates:[...(state.wrong[k]?.dates||[]),todayStr()].slice(-20)}; updateReview(k,ok); save(); updateAll(); renderMissList(); nextQuestion(); }
function undoLastMark(){ if(!lastMark){ alert('取り消せる採点がない'); return; } const lm=lastMark, k=key(lm.item.deck,lm.item.no); state.today=lm.prevToday; state.history[lm.date]=lm.prevHistory; if(lm.prevWrong) state.wrong[k]=lm.prevWrong; else delete state.wrong[k]; if(lm.prevReview) state.review[k]=lm.prevReview; else delete state.review[k]; current=lm.item; answerShown=true; const mode=document.getElementById('mode').value; document.getElementById('qno').textContent=`${DECKS[current.deck].name} No.${current.no}　採点を取り消しました`; document.getElementById('question').textContent=mode==='word2meaning'?current.word:current.meaning; document.getElementById('answer').textContent=mode==='word2meaning'?current.meaning:current.word; document.getElementById('answer').style.display='block'; setMarkButtons(true); lastMark=null; save(); updateAll(); renderMissList(); }
function toggleStar(){ if(!current) return; const k=key(current.deck,current.no); state.star[k]=!state.star[k]; if(!state.star[k]) delete state.star[k]; save(); updateAll(); }
function updateStats(){ ensureToday(); const t=state.today; document.getElementById('done').textContent=t.done; document.getElementById('ok').textContent=t.ok; document.getElementById('ng').textContent=t.ng; document.getElementById('rate').textContent=t.done?Math.round(t.ok/t.done*100)+'%':'-'; }
function updateReviewSummary(){ const due=dueKeys(0), tomorrow=dueKeys(1).filter(k=>!due.includes(k)); const grad=Object.values(state.review).filter(r=>r.graduated).length; document.getElementById('dueCount').textContent=due.length; document.getElementById('tomorrowCount').textContent=tomorrow.length; document.getElementById('gradCount').textContent=grad; document.getElementById('streakCount').textContent=getStreak()+'日'; document.getElementById('reviewHint').textContent=due.length?`今日やる復習が ${due.length} 語ある。最優先で潰そう。`:'🎉 今日の復習は完了しています。範囲テストかミス単語を進めよう。'; }
function itemByKey(k){ const [deck,no]=k.split(':'); return allItems(deck).find(x=>String(x.no)===no); }
function renderMissList(){ const el=document.getElementById('missList'); if(!el) return; const deck=document.getElementById('missDeck')?.value||'all'; const f=(document.getElementById('missFilter')?.value||'').toLowerCase(); let rows=Object.entries(state.wrong).map(([k,v])=>({k,v,item:itemByKey(k)})).filter(x=>x.item); if(deck!=='all') rows=rows.filter(x=>x.item.deck===deck); if(f) rows=rows.filter(x=>String(x.item.no).includes(f)||x.item.word.toLowerCase().includes(f)||x.item.meaning.toLowerCase().includes(f)); rows.sort((a,b)=>(b.v.count||0)-(a.v.count||0)); if(!rows.length){ el.innerHTML='<p class="small">ミス単語なし。強い。</p>'; return; } el.innerHTML='<table class="table"><thead><tr><th>教材</th><th>No</th><th>単語/熟語</th><th>意味</th><th>回数</th><th></th></tr></thead><tbody>'+rows.map(r=>`<tr><td>${DECKS[r.item.deck].name}</td><td>${r.item.no}</td><td><b>${escapeHtml(r.item.word)}</b><br><span class="small">最終: ${r.v.last||'-'}</span></td><td>${escapeHtml(r.item.meaning)}</td><td>${r.v.count||1}</td><td><button onclick="deleteMiss('${r.k}')">削除</button></td></tr>`).join('')+'</tbody></table>'; }
function deleteMiss(k){ delete state.wrong[k]; save(); renderMissList(); updateAll(); }
function startMissSession(){ const deck=document.getElementById('missDeck')?.value||'all'; document.getElementById('deck').value=deck; document.getElementById('source').value='wrong'; onDeckChange(); location.hash='#study'; setTimeout(()=>startSession(),50); }
function startReviewSession(){ const due=dueKeys(0); if(!due.length){ alert('🎉 今日の復習は完了しています'); updateReviewSummary(); return; } const dueSet=new Set(due); pool=allItems('all').filter(w=>dueSet.has(key(w.deck,w.no))); if(!pool.length){ alert('復習対象を読み込めませんでした。設定→忘却曲線リセットで直る可能性があります。'); return; } document.getElementById('deck').value='all'; document.getElementById('source').value='review'; const pc=document.getElementById('poolCount'); if(pc) pc.textContent=pool.length; queue=document.getElementById('order').value==='random'?shuffle([...pool]):[...pool]; sessionKey='review:'+todayStr()+':'+pool.map(w=>key(w.deck,w.no)).join(','); usedBySession[sessionKey]=new Set(); current=null; location.hash='#study'; setTimeout(()=>nextQuestion(),50); }
function runSearch(){ const deck=document.getElementById('searchDeck')?.value||'all'; const q=(document.getElementById('searchBox')?.value||'').trim().toLowerCase(); const el=document.getElementById('searchResults'); if(!el) return; if(!q){ el.innerHTML='<p class="small">検索語を入れて。</p>'; return; } let rows=allItems(deck).filter(w=>String(w.no).includes(q)||w.word.toLowerCase().includes(q)||w.meaning.toLowerCase().includes(q)).slice(0,100); el.innerHTML=rows.length?rows.map(w=>`<div class="resultItem"><span class="badge">${DECKS[w.deck].name} No.${w.no}</span><br><b>${escapeHtml(w.word)}</b><br><span>${escapeHtml(w.meaning)}</span><br><button onclick="addMiss('${w.deck}',${w.no})">ミス単語へ追加</button> <button onclick="addStar('${w.deck}',${w.no})">★</button> <button onclick="studyOne('${w.deck}',${w.no})">これを出題</button></div>`).join(''):'<p class="small">見つからなかった。</p>'; }
function addMiss(deck,no){ const k=key(deck,no); state.wrong[k]={count:(state.wrong[k]?.count||0)+1,last:new Date().toLocaleDateString('ja-JP'),dates:[...(state.wrong[k]?.dates||[]),todayStr()].slice(-20)}; save(); alert('ミス単語帳に追加した'); updateAll(); }
function addStar(deck,no){ state.star[key(deck,no)]=true; save(); alert('★に追加した'); updateAll(); }
function studyOne(deck,no){ document.getElementById('deck').value=deck; document.getElementById('source').value='range'; document.getElementById('startNo').value=no; document.getElementById('endNo').value=no; onDeckChange(); location.hash='#study'; setTimeout(()=>startSession(),50); }
function addTestEvent(){ const name=document.getElementById('testName').value.trim()||'ターゲットテスト'; const date=document.getElementById('testDate').value; const deck=document.getElementById('testDeck').value; const max=DECKS[deck].max; const s=clamp(document.getElementById('testStart').value,1,max), e=clamp(document.getElementById('testEnd').value,1,max); if(!date) return alert('日付を入れて'); state.tests.push({id:Date.now(),name,date,deck,start:Math.min(s,e),end:Math.max(s,e),memo:document.getElementById('testMemo').value.trim()}); save(); renderCalendar(); renderNextTest(); document.getElementById('testName').value=''; document.getElementById('testMemo').value=''; }
function renderCalendar(){ const el=document.getElementById('calendarList'); if(!el) return; const t=todayStr(); const rows=[...state.tests].sort((a,b)=>a.date.localeCompare(b.date)); if(!rows.length){ el.innerHTML='<p class="small">まだ予定なし。</p>'; return; } el.innerHTML=rows.map(ev=>`<div class="calendarDay"><span class="badge${ev.date<t?'':' due'}">${displayDate(ev.date)}</span> <b>${escapeHtml(ev.name)}</b><br>${DECKS[ev.deck].name} No.${ev.start}〜${ev.end}<br><span class="small">${escapeHtml(ev.memo||'')}</span><div class="row" style="margin-top:8px"><button class="primary" onclick="studyRange('${ev.deck}',${ev.start},${ev.end})">この範囲を勉強</button><button class="bad" onclick="deleteTestEvent(${ev.id})">削除</button></div></div>`).join(''); }
function deleteTestEvent(id){ if(!confirm('この予定を削除する？')) return; state.tests=state.tests.filter(e=>e.id!==id); save(); renderCalendar(); renderNextTest(); }
function studyRange(deck,s,e){ document.getElementById('deck').value=deck; document.getElementById('source').value='range'; document.getElementById('startNo').value=s; document.getElementById('endNo').value=e; onDeckChange(); location.hash='#study'; setTimeout(()=>startSession(),50); }
function renderNextTest(){ const el=document.getElementById('nextTestBox'); if(!el) return; const t=todayStr(); const next=[...state.tests].filter(e=>e.date>=t).sort((a,b)=>a.date.localeCompare(b.date))[0]; if(!next){ el.innerHTML='未登録。カレンダーから追加できる。'; return; } el.innerHTML=`<b>${displayDate(next.date)} ${escapeHtml(next.name)}</b><br>${DECKS[next.deck].name} No.${next.start}〜${next.end}<br><button class="primary" style="margin-top:8px" onclick="studyRange('${next.deck}',${next.start},${next.end})">この範囲を勉強</button>`; }
function getStreak(){ const dates=Object.keys(state.history).filter(d=>(state.history[d]?.done||0)>0).sort().reverse(); if(!dates.length) return 0; let count=0, d=todayStr(); for(;;){ if((state.history[d]?.done||0)>0){ count++; d=addDays(d,-1); } else break; } return count; }
function renderStatsPage(){ const h=state.history||{}, t=todayStr(); const weekStart=addDays(t,-6), monthStart=t.slice(0,8)+'01'; const sum=(from)=>Object.entries(h).filter(([d])=>d>=from&&d<=t).reduce((a,[,v])=>a+(v.done||0),0); document.getElementById('statToday').textContent=h[t]?.done||0; document.getElementById('statWeek').textContent=sum(weekStart); document.getElementById('statMonth').textContent=sum(monthStart); document.getElementById('statStreak').textContent=getStreak()+'日'; const rows=Object.entries(h).sort((a,b)=>b[0].localeCompare(a[0])).slice(0,30); document.getElementById('historyList').innerHTML=rows.length?'<table class="table"><tr><th>日付</th><th>解答</th><th>正解</th><th>ミス</th><th>率</th></tr>'+rows.map(([d,v])=>`<tr><td>${displayDate(d)}</td><td>${v.done||0}</td><td>${v.ok||0}</td><td>${v.ng||0}</td><td>${v.done?Math.round((v.ok||0)/v.done*100)+'%':'-'}</td></tr>`).join('')+'</table>':'<p class="small">履歴なし。</p>'; renderRanking(); }
function renderRanking(){ const rows=Object.entries(state.wrong).map(([k,v])=>({k,v,item:itemByKey(k)})).filter(x=>x.item).sort((a,b)=>(b.v.count||0)-(a.v.count||0)).slice(0,20); const el=document.getElementById('rankingList'); if(!el) return; el.innerHTML=rows.length?'<table class="table"><tr><th>順位</th><th>単語</th><th>回数</th></tr>'+rows.map((r,i)=>`<tr><td>${i+1}</td><td><span class="badge">${DECKS[r.item.deck].name} No.${r.item.no}</span><br><b>${escapeHtml(r.item.word)}</b><br><span class="small">${escapeHtml(r.item.meaning)}</span></td><td>${r.v.count||1}</td></tr>`).join('')+'</table>':'<p class="small">まだランキングなし。</p>'; }
function resetPart(part){ const names={today:'今日の統計',history:'学習履歴',wrong:'ミス単語帳',star:'お気に入り',review:'忘却曲線',tests:'テスト予定',all:'全データ'}; if(!confirm(`${names[part]}を消す？`)) return; if(part==='today') state.today={date:todayStr(),done:0,ok:0,ng:0}; else if(part==='history') state.history={}; else if(part==='wrong') state.wrong={}; else if(part==='star') state.star={}; else if(part==='review') state.review={}; else if(part==='tests') state.tests=[]; else if(part==='all') state={wrong:{},star:{},today:{date:todayStr(),done:0,ok:0,ng:0},history:{},review:{},tests:[]}; save(); updateAll(); alert('消した'); }
function escapeHtml(s){ return String(s).replace(/[&<>"']/g, m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m])); }
function updateAll(){ updateStats(); updateReviewSummary(); renderNextTest(); if(location.hash==='#miss') renderMissList(); if(location.hash==='#calendar') renderCalendar(); if(location.hash==='#stats') renderStatsPage(); buildPool(); }
function route(){ const h=location.hash||'#study'; document.getElementById('studyPage').classList.toggle('hide',h!=='#study'); document.getElementById('missPage').classList.toggle('hide',h!=='#miss'); document.getElementById('searchPage').classList.toggle('hide',h!=='#search'); document.getElementById('calendarPage').classList.toggle('hide',h!=='#calendar'); document.getElementById('statsPage').classList.toggle('hide',h!=='#stats'); document.getElementById('settingsPage').classList.toggle('hide',h!=='#settings'); if(h==='#miss') renderMissList(); if(h==='#search') runSearch(); if(h==='#calendar') renderCalendar(); if(h==='#stats') renderStatsPage(); updateAll(); }
window.addEventListener('hashchange',route); normalizeState(); ensureToday(); onDeckChange(); updateAll(); route(); if('serviceWorker' in navigator) navigator.serviceWorker.register('./sw.js').catch(()=>{});
